# Generated by Django 2.2.4 on 2019-10-20 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('status', models.BooleanField(default=False)),
                ('env', models.CharField(max_length=20, verbose_name='env')),
                ('version', models.CharField(max_length=5, verbose_name='version')),
                ('address', models.GenericIPAddressField(null=True, validators=[django.core.validators.validate_ipv4_address])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('level', models.CharField(choices=[('critical', 'critical'), ('debug', 'debug'), ('error', 'error'), ('warning', 'warning'), ('information', 'information')], max_length=20, verbose_name='level')),
                ('data', models.TextField(verbose_name='data')),
                ('archived', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='events.Agent')),
            ],
        ),
    ]
