# Generated by Django 2.2.4 on 2019-10-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='env',
            field=models.CharField(choices=[('producao', 'producao'), ('homologacao', 'homologacao'), ('dev', 'dev')], max_length=20, verbose_name='env'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.IntegerField(choices=[(5, 'critical'), (4, 'debug'), (3, 'error'), (2, 'warning'), (1, 'information')], verbose_name='level'),
        ),
    ]
