# Generated by Django 2.2.4 on 2019-10-13 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('env', models.CharField(max_length=20, verbose_name='env')),
                ('arquivado', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_login', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('level', models.CharField(max_length=20, verbose_name='level')),
                ('detalhes', models.TextField(verbose_name='descricao')),
                ('origem', models.CharField(max_length=254, verbose_name='origem')),
                ('date', models.DateField(default=datetime.date.today)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='api.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='api.User')),
            ],
        ),
    ]
