# Generated by Django 2.2.4 on 2019-10-15 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('status', models.BooleanField(default=False)),
                ('env', models.CharField(max_length=20, verbose_name='env')),
                ('version', models.CharField(max_length=5, verbose_name='env')),
                ('address', models.CharField(max_length=39, verbose_name='name')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='event',
            name='env',
        ),
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.TextField(default='none', verbose_name='data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(default=1, max_length=20, verbose_name='level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='none', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='event',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='api.Agent'),
        ),
    ]
