# Generated by Django 2.2.4 on 2019-10-15 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20191014_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='arquivado',
            new_name='archived',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='date',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(null=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.CharField(max_length=5, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('critical', 'critical'), ('debug', 'debug'), ('error', 'error'), ('warning', 'warning'), ('information', 'information')], max_length=20, verbose_name='level'),
        ),
    ]
